### ISSUE TITLE
App runs full screen but offers no option to exit

### ISSUE THREAD

**Issue by TheLastProject** [KOBUGE-Games/Ninja-Training#1]
Ninja Training runs full screen, hiding the back and home buttons, without providing its own exit button. This makes it a lot harder to quickly close the app than should be necessary.

It would be better to not run full screen, or add a menu/exit button somewhere, so that users can close or switch away from the app more easily.

**Comment by alketii** [comment]
The game is not full screen. What OS and Godot version are you using ?

**Comment by TheLastProject** [comment]
Sorry, I forgot Godot games are multi-platform. I'm running Android 5.1.1 (CyanogenMod 12.1). I got it from F-Droid, which seems to use okamstudio/godot@d3b42e41b0e446938d6634c8783e575de3d0b60f, so 1.1-stable ([Build recipe](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.kobuge.ninjatraining.txt#L22))

It hides the navigation keys (back/home/menu) and the bar Android has on the top, so literally the whole screen is covered by the game. Android calls this "Immersive Mode", and it looks like image 3 on https://developer.android.com/training/system-ui/immersive.html.

**Comment by akien-mga** [comment]
@alketii You'd have to turn this to false if you don't want immersive mode for Android: https://github.com/KOBUGE-Games/Ninja-Training/blob/master/export.cfg#L176

**Comment by alketii** [comment]
ok, changed it. Will try to make a release tonight.
Thanks @TheLastProject @akien-mga

**Comment by bojidar-bg** [comment]
Close?

**Comment by est31** [comment]
I guess so. 75c655d63d6af70716c7c85b12a8a156976e5b1e seems to have fixed this.
