### ISSUE TITLE
How compiling or packaging the app?

### ISSUE THREAD

**Issue by ghost** [KOBUGE-Games/Ninja-Training#3]
Hi.
I wonder how compiling or packaging the app, and what are the needed tools.
Regards.

**Comment by bojidar-bg** [comment]
The needed tools are [Godot (Open-source game engine)](http://www.godotengine.org/projects/godot-engine), [export templates](http://www.godotengine.org/projects/godot-engine/documents) and  [android SDK](http://developer.android.com/sdk/index.html). Most of the instructions are outlined in [Godot's wiki](https://github.com/godotengine/godot/wiki/export_android).

**Comment by ghost** [comment]
Ok, thanks.
